name: Docker CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t callprotect/backend-server:latest .

      - name: Push Docker image
        run: docker push callprotect/backend-server:latest

      - name: Create .env.prod from secret
        run: echo "${{ secrets.ENV_PROD }}" > .env.prod

      - name: Copy .env.prod to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env.prod"
          target: "/home/ubuntu/"
          debug: true
          timeout: 180s

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/CallProtector_BE

            echo "ğŸ“¦ Pull latest backend image"
            docker pull callprotect/backend-server:latest

            echo "ğŸ§¹ Stop and remove existing containers"
            docker-compose down

            echo "ğŸ“ Apply latest env file"
            cp /home/ubuntu/.env.prod .env.prod

            echo "ğŸš€ Launch all services with docker-compose"
            docker-compose up -d --build
